{
 "title": "pt-stalk Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "MySQL Processlist",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "target": "processlist", "type": "table" }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Connections_delta", "type": "timeseries" },
    { "target": "Max_used_connections", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Aborted_clients_delta", "type": "timeseries" },
    { "target": "Aborted_connects_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Threads_running", "type": "timeseries" },
    { "target": "Threads_connected", "type": "timeseries" },
    { "target": "Connections_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Threads_created_delta", "type": "timeseries" },
    { "target": "Threads_connected", "type": "timeseries" },
    { "target": "Threads_cached", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Temporary Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Created_tmp_disk_tables_delta", "type": "timeseries" },
    { "target": "Created_tmp_files_delta", "type": "timeseries" },
    { "target": "Created_tmp_tables_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Slow_queries_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Select_full_join_delta", "type": "timeseries" },
    { "target": "Select_range_delta", "type": "timeseries" },
    { "target": "Select_range_check_delta", "type": "timeseries" },
    { "target": "Select_scan_delta", "type": "timeseries" },
    { "target": "Select_full_range_join_delta", "type": "timeseries" },
    { "target": "Select_scan_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Sorts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Sort_merge_passes_delta", "type": "timeseries" },
    { "target": "Sort_rows_delta", "type": "timeseries" },
    { "target": "Sort_range_delta", "type": "timeseries" },
    { "target": "Sort_scan_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Table_locks_immediate_delta", "type": "timeseries" },
    { "target": "Table_locks_waited_delta", "type": "timeseries" },
    { "target": "Sort_range_delta", "type": "timeseries" },
    { "target": "Sort_scan_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Questions and Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Questions_delta", "type": "timeseries" },
    { "target": "Queries_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Bytes_received_delta", "type": "timeseries" },
    { "target": "Bytes_sent_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Com_stmt_execute_delta", "type": "timeseries" },
    { "target": "Com_update_delta", "type": "timeseries" },
    { "target": "Com_delete_delta", "type": "timeseries" },
    { "target": "Com_begin_delta", "type": "timeseries" },
    { "target": "Com_insert_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Handler_read_first_delta", "type": "timeseries" },
    { "target": "Handler_read_key_delta", "type": "timeseries" },
    { "target": "Handler_read_last_delta", "type": "timeseries" },
    { "target": "Handler_read_next_delta", "type": "timeseries" },
    { "target": "Handler_read_prev_delta", "type": "timeseries" },
    { "target": "Handler_read_rnd_delta", "type": "timeseries" },
    { "target": "Handler_read_rnd_next_delta", "type": "timeseries" },
    { "target": "Handler_rollback_delta", "type": "timeseries" },
    { "target": "Handler_savepoint_delta", "type": "timeseries" },
    {
     "target": "Handler_savepoint_rollback_delta",
     "type": "timeseries"
    },
    { "target": "Handler_update_delta", "type": "timeseries" },
    { "target": "Handler_write_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Handler Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Handler_read_first_delta", "type": "timeseries" },
    { "target": "Handler_read_key_delta", "type": "timeseries" },
    { "target": "Handler_read_last_delta", "type": "timeseries" },
    { "target": "Handler_read_next_delta", "type": "timeseries" },
    { "target": "Handler_read_prev_delta", "type": "timeseries" },
    { "target": "Handler_read_rnd_delta", "type": "timeseries" },
    { "target": "Handler_read_rnd_next_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Com_commit_delta", "type": "timeseries" },
    { "target": "Com_update_delta", "type": "timeseries" },
    { "target": "Com_rollback_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Open_files", "type": "timeseries" },
    { "target": "Innodb_num_open_files", "type": "timeseries" }
   ]
  },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Table_open_cache_hits_delta", "type": "timeseries" },
    { "target": "Table_open_cache_misses_delta", "type": "timeseries" },
    {
     "target": "Table_open_cache_overflows_delta",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "MySQL Table Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "Open_tables", "type": "timeseries" },
    { "target": "Opened_table_definitions_delta", "type": "timeseries" },
    { "target": "Opened_tables_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    { "target": "Innodb_buffer_pool_reads_delta", "type": "timeseries" },
    {
     "target": "Innodb_buffer_pool_read_requests_delta",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "InnoDB IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    { "target": "Innodb_data_pending_fsyncs", "type": "timeseries" },
    { "target": "Innodb_data_pending_reads", "type": "timeseries" },
    { "target": "Innodb_data_pending_writes", "type": "timeseries" },
    { "target": "Innodb_os_log_pending_fsyncs", "type": "timeseries" },
    { "target": "Innodb_os_log_pending_writes", "type": "timeseries" }
   ]
  },
  {
   "title": "InnoDB LSN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    { "target": "Innodb_lsn_flushed_delta", "type": "timeseries" },
    { "target": "Innodb_lsn_current_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "InnoDB Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    { "target": "Innodb_rows_inserted_delta", "type": "timeseries" },
    { "target": "Innodb_rows_deleted_delta", "type": "timeseries" },
    { "target": "Innodb_rows_read_delta", "type": "timeseries" },
    { "target": "Innodb_rows_updated_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "InnoDB OS Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    { "target": "Innodb_os_log_written_delta", "type": "timeseries" }
   ]
  },
  {
   "title": "Innodb Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    { "target": "Innodb_log_waits", "type": "timeseries" }
   ]
  }
 ]
}